#!/bin/bash
#
# A script run in User Data of the bastion host during boot.
#
# Note that this script expects to be running in an AMI generated by the Packer template packer/bastion-host.json.

set -e

# Send the log output from this script to user-data.log, syslog, and the console
# From: https://alestic.com/2010/12/ec2-user-data-output/
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

function start_cloudwatch_logs_agent {
  local readonly vpc_name="$1"
  local readonly log_group_name="$2"

  echo "Starting CloudWatch Logs Agent in VPC $vpc_name"
  /etc/user-data/cloudwatch-log-aggregation/run-cloudwatch-logs-agent.sh --vpc-name "$vpc_name" --log-group-name "$log_group_name"
}

function start_fail2ban {
  echo "Starting fail2ban"
  /etc/user-data/configure-fail2ban-cloudwatch/configure-fail2ban-cloudwatch.sh --cloudwatch-namespace Fail2Ban
}

start_cloudwatch_logs_agent "${vpc_name}" "${log_group_name}"
start_fail2ban

# Lock down the EC2 metadata endpoint so only the root user can access it
/usr/local/bin/ip-lockdown 169.254.169.254 root
